apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-docker-deployment
  labels:
    app: node-app-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app-docker
  template:
    metadata:
      labels:
        app: node-app-docker
    spec:
      containers:
      - name: node-app-docker
        image: xyz9999/node-app-docker-49:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-docker-service
spec:
  type: NodePort
  selector:
    app: node-app-docker
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100